version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      
  # Maintain dependencies for .NET
  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    assignees:
      - 'mstonis'
    commit-message:
      prefix: 'deps'
      include: 'scope'